# Numpy

In [ ]:
#It is array processing package (i.e we use to deal with arrays)
#It holds same datatype unlike lists

In [1]:
#Importing package numpy

import numpy as np

In [3]:
#1-Dimentional array

my_lst=[1,2,3,4,5,]
print(type(my_lst))
arr=np.array(my_lst)
print(type(arr))
arr

<class 'list'>
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [4]:
#check the dimention of array
arr.shape

(5,)

In [2]:
#2-Dimentional array

lst1=[1,2,3,4,5]
lst2=[6,7,8,9,0,]
lst3=[4,5,6,7,8]

arr11=np.array([lst1,lst2,lst3])
arr11

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [4, 5, 6, 7, 8]])

In [6]:
arr11.shape
#displaying 3rows and 5 columns

(3, 5)

In [19]:
arr11.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 4, 5],
       [6, 7, 8]])

In [27]:
arr2 = np.array([1, 2, 3, 4], ndmin=5) # ndim tells what dimention the particular array is 

print(arr2)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 1


In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
'''And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6'''

6


## indexing

In [3]:
arr11

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [4, 5, 6, 7, 8]])

In [8]:
#retreeving data from multidimentional array
arr11[0:2,0:1]
arr11[1:,1:4],arr11[1:,2:3]  #can retrive multiple arrayb output by using comma in a single line.

(array([[7, 8, 9],
        [5, 6, 7]]),
 array([[8],
        [6]]))

In [45]:
arr11[1:3,1:2] # includes the start index,but excludes end index

array([[7],
       [5]])

In [49]:
arr11[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [51]:
arr11[1:,2:4]

array([[8, 9],
       [6, 7]])

In [53]:
arr11[1:2,1:4]

array([[7, 8, 9]])

In [19]:
#inbuiltfunctions on array and numpy

arr=np.arange(1,10) # gives you array of mentioned range
print(arr)
arr=np.arange(0,10,step=3) # gives you array of (stat,stop,stepin the range)
arr

[1 2 3 4 5 6 7 8 9]


array([0, 3, 6, 9])

In [63]:
arr=np.linspace(1,10,50) # picks equally divided elements in the given range[ex: in range 1 to 10, 50 equally divided elelments]
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [23]:
#copy() and broadcasting

lst=[1,2,3,4,5,6,7,8,9]
arr1=np.array(lst)
print(type(arr1))
arr1

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#broadcasting ---- replacing the array with the given index.
arr1[3:8]=100
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100,   9])

In [24]:
arr2=arr1
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2[3:]=500
arr2

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [26]:
arr1
#arr1 is also effected by the values change in arr2 as array share one single memory set to prevent this we use copy()

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [78]:
arr3=arr1.copy()
print(arr1)
arr3[4:]=999
print(arr3)

#arr3 is having seperate memory set as we have copied the data to a new variable by using copyfunction "copy()"

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 999 999 999 999 999]


In [90]:
#conditions used in Exploratory Data Analysis.


#conditions on array, it checks each and every element like for loop
val=2
print(arr1<2) #returns boolean value
print(arr1/2)
print(arr1*val)
print(arr1%val) 
print(val*arr1)
print(arr1>2)
print(arr1[arr1>2]) #to get values put the condition into array

[ True False False False False False False False False]
[  0.5   1.    1.5 250.  250.  250.  250.  250.  250. ]
[   2    4    6 1000 1000 1000 1000 1000 1000]
[1 0 1 0 0 0 0 0 0]
[   2    4    6 1000 1000 1000 1000 1000 1000]
[False False  True  True  True  True  True  True  True]
[  3 500 500 500 500 500 500]


In [94]:
ar1=np.arange(0,10).reshape(2,5)
print(ar1)
ar2=np.arange(0,10).reshape(2,5)
print(ar2)
ar1*ar2

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [99]:
#ones

np.ones(5)
# by default ones is float

array([1., 1., 1., 1., 1.])

In [29]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [100]:
#converting the ones to integer
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [102]:
np.ones((2,5),dtype=int)  #multi-D array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
'''There are a lot of functions for changing the shapes of arrays in numpy flatten,
ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc.
These fall under Intermediate to Advanced section of numpy.'''

In [109]:
#Random Distribution ---- All the value are random and not permanent, they are choosen randomly for each iteration

np.random.rand(5)

array([0.64599427, 0.3992838 , 0.17237679, 0.36116304, 0.34221058])

In [110]:
np.random.rand(5,5)

array([[0.16414417, 0.142931  , 0.41127323, 0.63903209, 0.85307966],
       [0.02123051, 0.93946979, 0.12548611, 0.2573742 , 0.95245426],
       [0.25553201, 0.20720888, 0.94071331, 0.6539983 , 0.4515753 ],
       [0.48524232, 0.95098507, 0.43728047, 0.578992  , 0.88042566],
       [0.56487336, 0.65831467, 0.67418984, 0.98149799, 0.51181488]])

In [111]:
np.random.randn(4)

array([-1.17171588,  1.1070246 , -0.09079429,  0.9557188 ])

In [108]:
np.random.randn(4,4)

array([[-0.06379175, -0.08593999, -0.40282419,  0.72062405],
       [ 0.44473406, -0.79061218, -0.4728046 ,  1.28560531],
       [-1.11969485, -1.27465494, -0.55303329,  0.55628153],
       [ 0.80802469,  0.01445972,  0.69260775,  0.54832824]])

In [4]:
np.random.randint(0,100,5)   #selects 5 values in the range of 0-100 as per condition

array([96, 25, 61, 84, 42])

In [123]:
np.random.randint(0,100,6).reshape(3,2)

array([[87, 63],
       [28, 84],
       [ 9, 86]])

In [116]:
np.random.random_sample((1,8))  #returns values from 0.0 to 1.0

array([[0.44149942, 0.76031601, 0.75053427, 0.09679261, 0.15958765,
        0.60093624, 0.7452381 , 0.28552053]])

In [3]:
np.random.random_sample((1,5))

array([[0.62236827, 0.18068793, 0.44536778, 0.79995702, 0.98598007]])

In [5]:
np.random.random_sample((2,5))

array([[0.51199511, 0.42646127, 0.20684957, 0.07385422, 0.22826787],
       [0.25554249, 0.43071615, 0.98489437, 0.56273262, 0.35456684]])

In [6]:
np.random.random_sample((1,3))

array([[0.81825996, 0.24247822, 0.00451427]])